function doc(){

    return {

        "title": "",
        "access": "confidential",
        "alert": "Yes",
        "alertStart": NumberLong(10),
        "approvalRequestEmails": [],
        "approvalRequestIds": [],
        "createdDate": ISODate(),
        "creatorId": "",
        "creatorName": "",
        "deleted": false,
        "docApprovalRequest": "",
        "docCategory": "",
        "docCategoryLabel": "",
        "docCategoryParents": "",
        "docDepartment": "",
        "docFileList": [],
        "docFiledata": {},
        "docFilename": "",
        "docFormat": "email",
        "docOpportunity": "",
        "docOpportunityId": "",
        "docOpportunityTitle": "",
        "docOriginalTemplate": "none",
        "docProject": "",
        "docProjectId": "",
        "docProjectTitle": "",
        "docRemarks": "",
        "docRevisionOf": "",
        "docShare": "",
        "docTag": "",
        "docTender": "",
        "docTenderId": "",
        "docTenderTitle": "",
        "effectiveDate": ISODate(),
        "expiring": NumberInt(2),
        "expiryDate": ISODate(),
        "interaction": "ro",
        "lastUpdate": ISODate(),
        "sharedEmails": [],
        "sharedIds": [],
        "tags": [],
        "templateName": "",
        "templateNumberStart": "1",
        "useAsTemplate": "No"

    }

}
